AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  BucketName:
    Type: String
    Default: my-awesome-bucket

Resources:
  StaticBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
