- hosts: localhost
  tasks:
    - name: install postgresql
      package: name=postgresql-server state=present

    - name: initialize postgresql
      command: /usr/bin/postgresql-setup initdb
      args:
        creates: /var/lib/pgsql/data/postgresql.conf
      
    - name: update config file
      lineinfile:
        path: /var/lib/pgsql/data/postgresql.conf
        regexp: '^synchronous_commit ='
        line: 'synchronous_commit = {{ pg_sync|default("on") }}'
      register: postgres_config

    - name: set to run on boot
      service: name=postgresql enabled=yes state=started

    - name: restart service
      service: name=postgresql state=restarted
      when: postgres_config.changed
