# The tasks below will run on the host or hosts specified. Ansible
# always has a default definition of 'localhost' (the same host
# running Ansible); for remote hosts, an inventory file must be
# created listing the host names and any necessary connection
# parameters.
- hosts: localhost

  # Tasks are defined as a list of objects and are executed in sequence.
  tasks:
    - name: enable epel repo
      # This task is required to make the nginx package available.
      package: name=epel-release state=present
        
    - name: install nginx
      # This task defines a package installation via the state=present
      # option.
      package: name=nginx state=present

    - name: set to run on boot
      # This configures the given service to be run on boot
      # (enabled=yes) and started (state=started).
      service: name=nginx enabled=yes state=started
