- hosts: localhost
  tasks:
    - name: enable epel repo
      package: name=epel-release state=present
        
    - name: install nginx
      package: name=nginx state=present

    - name: set to run on boot
      service: name=nginx enabled=yes state=started
