- hosts: localhost
  tasks:
    - name: enable epel repo
      command: /usr/bin/amazon-linux-extras install -y epel
      args:
        creates: /etc/yum.repos.d/epel.repo
        
    - name: install nginx
      package: name=nginx state=present

    - name: set to run on boot
      service: name=nginx enabled=yes state=started
